-- Core Tables
CREATE TABLE AIRPLANES (
    airplane_serial_number VARCHAR2(50) PRIMARY KEY,
    model VARCHAR2(100) NOT NULL,
    manufacturer VARCHAR2(100) NOT NULL,
    capacity NUMBER NOT NULL
);

CREATE TABLE AIRPORTS (
    airport_code VARCHAR2(10) PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    country VARCHAR2(100) NOT NULL
);

CREATE TABLE FLIGHTS (
    flight_number VARCHAR2(20) PRIMARY KEY,
    departure_airport_code VARCHAR2(10) NOT NULL,
    arrival_airport_code VARCHAR2(10) NOT NULL,
    departure_datetime TIMESTAMP NOT NULL,
    arrival_datetime TIMESTAMP NOT NULL,
    airplane_serial_number VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_departure_airport FOREIGN KEY (departure_airport_code) REFERENCES AIRPORTS(airport_code),
    CONSTRAINT fk_arrival_airport FOREIGN KEY (arrival_airport_code) REFERENCES AIRPORTS(airport_code),
    CONSTRAINT fk_airplane FOREIGN KEY (airplane_serial_number) REFERENCES AIRPLANES(airplane_serial_number)
);

CREATE TABLE PASSENGERS (
    passenger_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE,
    phone_number VARCHAR2(20)
);

-- Reservation and Ticketing Tables
CREATE TABLE RESERVATIONS (
    reservation_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id NUMBER NOT NULL,
    flight_number VARCHAR2(20) NOT NULL,
    seat_number VARCHAR2(10),
    reservation_status VARCHAR2(20) NOT NULL CHECK (reservation_status IN ('CONFIRMED', 'CANCELED', 'PENDING')),
    CONSTRAINT fk_passenger FOREIGN KEY (passenger_id) REFERENCES PASSENGERS(passenger_id),
    CONSTRAINT fk_flight FOREIGN KEY (flight_number) REFERENCES FLIGHTS(flight_number)
);

CREATE TABLE TICKETS (
    ticket_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id NUMBER NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    issuance_date DATE NOT NULL,
    CONSTRAINT fk_reservation FOREIGN KEY (reservation_id) REFERENCES RESERVATIONS(reservation_id)
);

-- Operational Tables
CREATE TABLE CREW_MEMBERS (
    crew_member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(100) NOT NULL,
    last_name VARCHAR2(100) NOT NULL,
    role VARCHAR2(50) NOT NULL CHECK (role IN ('PILOT', 'CO-PILOT', 'FLIGHT_ATTENDANT', 'CABIN_CREW'))
);

CREATE TABLE CREW_ASSIGNMENTS (
    assignment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number VARCHAR2(20) NOT NULL,
    crew_member_id NUMBER NOT NULL,
    CONSTRAINT fk_flight_assignment FOREIGN KEY (flight_number) REFERENCES FLIGHTS(flight_number),
    CONSTRAINT fk_crew_member FOREIGN KEY (crew_member_id) REFERENCES CREW_MEMBERS(crew_member_id)
);

CREATE TABLE AIRCRAFT_MAINTENANCE (
    maintenance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airplane_serial_number VARCHAR2(50) NOT NULL,
    maintenance_date DATE NOT NULL,
    description VARCHAR2(500) NOT NULL,
    technician_id VARCHAR2(50),
    CONSTRAINT fk_airplane_maintenance FOREIGN KEY (airplane_serial_number) REFERENCES AIRPLANES(airplane_serial_number)
);
